### ISSUE TITLE
Improve the consistency of the PINNBench/Burgers benchmark

### ISSUE THREAD

**Issue by Deathn0t** [deephyper/benchmark#3]
The PINNBench/Burgers benchmark should be improved in the following way:

- [ ] adapt to `deephyper==0.5.0` with receiving a `job:RunningJob` instead of config.
- [ ] `@profile` decorator should be used on the run-function.
- [ ] more metadata should be returned such as metrics, number of parameters and others [see Combo model](https://github.com/deephyper/benchmark/blob/main/lib/ECP-Candle/Pilot1/Combo/model.py) we should probably also define in the README all the `metadata` that Deep Neural Networks benchmark should return (see https://github.com/deephyper/benchmark/issues/4).
- [ ]  `TFKerasStopperCallback` integration should be use to make it compatible with multi-fidelity [see Combo hpo](https://github.com/deephyper/benchmark/blob/main/lib/ECP-Candle/Pilot1/Combo/hpo.py#L115)
- [ ] documentation should be added in the `README` of the benchmark: what is the problem, what are the scores, what are the run-times on some hardware, what is the baseline (neural network and related problem in general) etc...

**Comment by iamyixuan** [comment]
- [x]  adapt to deephyper==0.5.0 with receiving a `job:RunningJob` instead of config.
- [x] `@profile` decorator should be used on the run-function.
- [x]  more metadata should be returned such as metrics, number of parameters and others [see Combo model](https://github.com/deephyper/benchmark/blob/main/lib/ECP-Candle/Pilot1/Combo/model.py) we should probably also define in the README all the metadata that Deep Neural Networks benchmark should return (see https://github.com/deephyper/benchmark/issues/4).
- [ ] TFKerasStopperCallback` ~~integration should be use to make it compatible with multi-fidelity [see Combo hpo](https://github.com/deephyper/benchmark/blob/main/lib/ECP-Candle/Pilot1/Combo/hpo.py#L115)~~
- [x] documentation should be added in the README of the benchmark: what is the problem, what are the scores, what are the run-times on some hardware, what is the baseline (neural network and related problem in general) etc...

Finished the above tasks - `TFKerasStopperCallback` not implemented as the model in `PINNBench` is not complied with keras.

**Comment by Deathn0t** [comment]
Completed in https://github.com/deephyper/benchmark/pull/10
