### ISSUE TITLE
Create Multi-Objective Black-Box Optimization Benchmarks

### ISSUE THREAD

**Issue by Deathn0t** [deephyper/benchmark#5]
Similarly to [C-BBO benchmarks](https://github.com/deephyper/benchmark/tree/main/lib/C-BBO) some continuous benchmarks for continuous black-box optimization can should be created. They could be added in the same folder as `C-BBO` with some specific prefix/suffix to show that they are Multi-Objectives. Then the [C-BBO table](https://github.com/deephyper/benchmark/blob/main/lib/C-BBO/README.md) can be updated accordingly.

**Comment by Deathn0t** [comment]
Merged https://github.com/deephyper/benchmark/pull/8 which adds the `DTLZBenchmark` for MOO.

**Comment by Deathn0t** [comment]
Are JAHS-Bench problems working or do we still need to work on it?

**Comment by thchang** [comment]
FYI, I think this probably belongs under #6 and we should close this issue, but to answer your question:

Yes I JAHS-Bench working in DeepHyper in my fork:

https://github.com/thchang/benchmark/tree/main/lib/JAHSBench

Need to make some small modifications to let user set problem params from CL and download datasets on install, but otherwise it is working.  Note that JAHS-Bench doesn't work on MacOS, so that is one limitation without any workaround.
